[package]
name = "game_launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game = { path = "../../../Game/game" }
sfcore = { path = "../../engine/sfcore" }